const url = 'https://api.coincap.io/v2/assets';

const showDom = (dataFromAPI = 'nothing was passed') => {
  const ul = document.getElementById('criptoContainer');

  const li = document.createElement('li');
  li.textContent = dataFromAPI;
  ul.appendChild(li);
};

// Nome da moeda (símbolo da moeda): valor em dólares . Exemplo: Bitcoin (BTC): 46785.06. 
const fetchURL = () => {
  const objReq = {
    method: 'GET',
    headers: { Accept: 'application/json' },
  };
  fetch(url, objReq)
    .then((response) => response.json())
    .then((data) => {
      // data.data.forEach((element, i) => {
      //   if(i < 10) showDom(`${element.name} (${element.symbol}): ${Number(element.priceUsd).toFixed(2)}`);
      // });
      return data.data.filter((element, i) => {
        if(i < 10) showDom(`${element.name} (${element.symbol}): $${Number(element.priceUsd).toFixed(2)}`);
      })
    })
    .catch((e) => console.error('error generated by query: ', e));
};
fetchURL();
