version: '3'
services:
  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - database
    # see https://hub.docker.com/_/ghost
    # see https://ghost.org/docs/config/ section -> configuration-options
    environment:
      database__client: mysql
      database__connection__host: database
      database__connection__user: root
      database__connection__password: 123456
      database__connection__database: ghost
    networks:
      - my-network

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db-data:

networks:
  my-network: