USE Scientists;
SELECT * FROM Scientists WHERE Name LIKE '%e%';
SELECT Name FROM Projects WHERE Code LIKE 'a%' ORDER BY Name;
SELECT * FROM Projects WHERE Code LIKE '%3%' ORDER BY Name;
SELECT * FROM AssignedTo WHERE Project IN('AeH3','Ast3', 'Che1');
SELECT * FROM Projects WHERE Hours > 500;
SELECT * FROM Projects WHERE Hours > 250 AND Hours < 800;
SELECT Name, Code FROM Projects WHERE Name NOT LIKE 'a%';
SELECT Name FROM Projects WHERE Code LIKE '%h%';
SHOW TABLES;