SET SQL_SAFE_UPDATES = 0;
USE sakila;
DELETE FROM film_actor WHERE actor_id = 12;
DELETE FROM actor WHERE actor_id = 12;
SELECT * FROM actor WHERE first_name = 'MATTHEW';
SELECT * FROM film_actor WHERE actor_id IN (8, 103, 181);
DELETE FROM film_actor WHERE actor_id IN (8, 103, 181);
DELETE FROM actor WHERE actor_id IN (8, 103, 181);
DELETE FROM film_text WHERE description LIKE '%saga%';
SELECT film_id FROM film_text WHERE description LIKE '%saga%';
TRUNCATE film_actor;
TRUNCATE film_category;